# Generated by Django 2.2.10 on 2022-08-17 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenceoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespart',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenceoria.Courses'),
        ),
    ]
