# Generated by Django 2.2.10 on 2022-08-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenceoria', '0002_auto_20220817_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvresume',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
