# Generated by Django 2.2.10 on 2022-08-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenceoria', '0003_auto_20220821_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IELTS',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='StudyAbroad',
        ),
        migrations.AlterField(
            model_name='cvresume',
            name='cv',
            field=models.FileField(default=1, upload_to='mediafiles_cdn/cv'),
            preserve_default=False,
        ),
    ]
