# Generated by Django 2.2.10 on 2022-09-09 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenceoria', '0005_auto_20220827_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('date', models.DateField(blank=True)),
                ('datetime', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eventspart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Contact', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenceoria.Events')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
