# Generated by Django 2.2.10 on 2022-09-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenceoria', '0006_events_eventspart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='duration',
        ),
    ]
