# Generated by Django 2.2.10 on 2022-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenceoria', '0007_remove_events_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyserv',
            name='How',
            field=models.CharField(choices=[('1', 'By email'), ('2', 'By phone')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studyserv',
            name='ServiceType',
            field=models.CharField(choices=[('1', 'Universities Application/Admission'), ('2', 'Admission Documents review'), ('3', 'Funding Assistance (Discounts, Scholarships, Teaching/Assistantships, & Loans)'), ('4', 'IELTS Tests')], max_length=20, null=True),
        ),
    ]
