# Generated by Django 2.2.10 on 2022-09-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenceoria', '0009_auto_20220915_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passengers',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passengers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_tickets', to='agenceoria.Passenger'),
        ),
    ]
