# Generated by Django 2.2.10 on 2022-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenceoria', '0010_auto_20220915_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvresume',
            name='Career_objective',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='Email',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='Telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='Year_admission_university',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='activities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='courses',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='experiences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='witnesses',
            field=models.TextField(null=True),
        ),
    ]
